language: csharp

os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 2.0.0

services:
  - docker

before_install:
  - docker pull andreysabitov/impala-kudu

script:
  - dotnet build src/Bongo
  - dotnet test test/Bongo.UnitTests
  - dotnet test test/Bongo.IntegrationTests
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then 
  dotnet pack src/Bongo --configuration Release /p:Version=$TRAVIS_TAG;
  nuget push src/Bongo/bin/Release/*.nupkg -ApiKey $API_KEY;
  fi"
